### ISSUE TITLE
Windows 10 x64 issue with Fiddle and libui

### ISSUE THREAD

**Issue by AndyObtiva** [kojix2/LibUI#32] opened 2021-09-29 22:58 UTC
I tried libui on Windows 10 x64 after installing Ruby 3.0.2 x64 via Ruby Windows Installer (and running `gem install glimmer-dsl-libui` to install gem + dependencies) and I keep getting this error upon loading libui:

```
$ ruby -r glimmer-dsl-libui -e "require 'examples/basic_window'"
e:/Ruby30-x64/lib/ruby/3.0.0/fiddle.rb:49:in `initialize': No such
file or directory (Fiddle::DLError)
        from e:/Ruby30-x64/lib/ruby/3.0.0/fiddle.rb:49:in `new'
        from e:/Ruby30-x64/lib/ruby/3.0.0/fiddle.rb:49:in `dlopen'
        from e:/Ruby30-x64/lib/ruby/3.0.0/fiddle/import.rb:86:in
`block in dlload'
        from e:/Ruby30-x64/lib/ruby/3.0.0/fiddle/import.rb:77:in `collect'
        from e:/Ruby30-x64/lib/ruby/3.0.0/fiddle/import.rb:77:in `dlload'
        from e:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/libui-0.0.10/lib/libui/ffi.rb:12:in
`<module:FFI>'
        from e:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/libui-0.0.10/lib/libui/ffi.rb:7:in
`<module:LibUI>'
        from e:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/libui-0.0.10/lib/libui/ffi.rb:6:in
`<top (required)>'
        from e:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/libui-0.0.10/lib/libui.rb:21:in
`require_relative'
        from e:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/libui-0.0.10/lib/libui.rb:21:in
`<module:LibUI>'
        from e:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/libui-0.0.10/lib/libui.rb:6:in
`<top (required)>'
        from <internal:e:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in
`require'
        from <internal:e:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in
`require'
        from e:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/glimmer-dsl-libui-0.1.4/lib/glimmer-dsl-libui.rb:31:in
`<top (required)>'
        from <internal:e:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in
`require'
        from <internal:e:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in
`rescue in require'
        from <internal:e:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:149:in
`require'
<internal:e:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in
`require': cannot load such file -- glimmer-dsl-libui (LoadError)
        from <internal:e:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in
`require'
```

I double checked the dll file path and the dll file does exist. 

I installed both the Ruby MSYS and MING toolchains by the way. I did see an odd error in the beginning:
```
mkdir: cannot change permissions of ‘/dev/shm’: Permission denied 
mkdir: cannot change permissions of ‘/dev/mqueue’: Permission denied
```

I am not sure if they are related at all.

Do you have any idea what is going on?

**Comment by kojix2** [comment] 2021-09-30 00:17
Hi! 
Thank you for your report!

> I double checked the dll file path and the dll file does exist.

I thought I might have forgotten to include the dll in the gem in the 0.0.10 release, but when I unzipped the gem file (actually a zip file), the dll file was included. Then I removed existing libui gem and installed the libui gem from the remote rubygem server on Windows, and it worked. So it is not that I forgot to put in the dll.

And I see some of your glimmer-dsl-libui examples worked on Windows.
Great work! (

![image](https://user-images.githubusercontent.com/5798442/135365309-94c3f29f-c9fc-4532-9268-4566d5ed28c7.png)

**Comment by AndyObtiva** [comment] 2021-09-30 00:22
Thanks for confirming that it works on Windows. Something must be wrong with my Windows setup (I installed it on my Mac via VirtualBox). It is Windows 10 Pro (OS Built 19043.1237). I will keep digging. Perhaps, I will try with a real Windows PC too once I get ahold of one over the weekend.

**Comment by kojix2** [comment] 2021-09-30 00:24
But I don't know what's wrong with your libui installation.
Sometimes you may be [using 32bit Ruby and libui will not work](https://github.com/kojix2/LibUI/issues/15). In that case, you need to download libui.dll manually.
See https://github.com/kojix2/LibUI#development

**Comment by rubyFeedback** [comment] 2021-09-30 15:58
I tested this on my windows 10 laptop, via the ruby one click installer, in a cmd.exe shell.

I could install libui 0.0.10 just fine; the examples also work (I noticed that I broke one of
my own examples recently in my gem ... when I have more time I have to fix tons of 
things in my libui-related gem ... right now I focus a bit more on ruby-gtk3 again. I
alternate a lot!).

I have not tested it in msys2/mingw. However had, that error actually seems familiar
to me. msys2/mingw is quite complicated (for me), but I think this may be an issue
more pertaining to msys2 perhaps.

I do not know how your error can be solved, but I think that error may not happen always.
I remember I uninstalled mingw once, and then set it up again, because I had no idea what
was going on anymore on windows. I think, but I am not sure, I did not install the msys2
environment from the ruby one click installer, and only used the msys2 installer + 64 bit.

What I can, however had, say is that libui 0.0.10 works on my win10 laptop. One main reason
why I use libui on windows is because I actually needed that for an elder relative who does not
know how to work with computers very well. One small backup utility I wrote just so that backing
up data is simpler. I just verified that the same code works on libui 0.0.10 - and it does!

So I think this issue is most likely more pertaining to something in the setup and msys2/mingw.

**Comment by AndyObtiva** [comment] 2021-10-08 01:18
I haven't had a chance to try a real Windows PC, but I uninstalled Ruby and tried to reinstall without msys as version 3.0.2, 2.7.4, 2.6.8 to no avail. Loading libui always resulted in that Fiddle error claiming the dll is not there when in fact it is there.

My Windows 10 installation in VirtualBox is definitely x64.

Here are the specs;
Edition	Windows 10 Pro
Version	21H1
Installed on	‎9/‎14/‎2021
OS build	19043.1237
Experience	Windows Feature Experience Pack 120.2212.3530.0

Device name	DESKTOP-OG3UV1I
Processor	Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz   2.49 GHz
Installed RAM	6.00 GB
Device ID	F086567A-34D5-48A3-8116-B7F09E19B97F
Product ID	00330-80000-00000-AA089
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

And, my Ruby definitely is x64 too. For example, here is what the 2.6 version says when I run `ruby --version`:
```
ruby 2.6.8p205 (2021-07-07 revision 67951) [x64-mingw32]
```

I will see if I get a chance in the near future to try on a real Windows PC instead of VirtualBox.

But, at least the specs above might give you a way to reproduce the problem by downloading the same exact version of Windows 10 from Microsoft and running on VirtualBox.

**Comment by rubyFeedback** [comment] 2021-12-03 20:34
I ran into that issue too just today after I reinstalled my win10 laptop. Very strange.

I'll try the manual way in a moment.

**Comment by kojix2** [comment] 2021-12-03 23:20
@rubyFeedback 
I have run LibUI on Windows, and have never had LibUI not work, either on a virtual box or on a real Windows computer. However, both Andy and shavy have experienced this problem on Windows. I think this error is very common. I can't help but wonder if other users are experiencing the same situation. I think there is some unknown reason why LibUI is not working on Windows.

**Comment by rubyFeedback** [comment] 2021-12-04 13:21
Heya kojix2,

I think I may be able to add some info actually.

So my laptop has some issue ... I think this is not directly related to windows per se, but something to do with the chipset.
It kind of becomes super-slow sometimes and "lags". I even have this sometimes on linux, but not as bad as on linux.

Anyway, I actually noticed that I used a Windows Home installation. So, on that laptop I installed Fedora, which works fine. And on my second desktop machine I now have installed Windows Pro (or Enterprise, but either way NOT the home version). And on that same machine (running an Intel chipset, and NOT Windows Home), I just tested libui + fiddle, and on a first installation it works. \o/

No problem on that computer.

I can not say whether this has something to do with Microsoft Home windows (perhaps some dll is missing or different there), or whether it has to do with the chipset in use, but I wanted to just give that feedback here in the event that someone else runs into such an error. So the two parts I would recommend others to look out for is:

(a) Home version versus pro/enterprise windows

AND

(b) chipset in use (I think some chipsets cause more issues, just as my lenovo laptop shows. I never have these issues on my desktop computers ... one of them I bought just recently and no issue there either, but the old chipset from 2014 had issues; booting sometimes stopped for no reason at all. I don't know whether this may impact fiddle or not, but perhaps the information may be useful for someone in the future)

**Comment by kojix2** [comment] 2021-12-04 15:27
@rubyFeedback 
Thanks for the reply.
I find it hard to believe that Home and Pro are different. If you run into the same situation again, download the compiled examples from the libui [release](https://github.com/andlabs/libui/releases) and see if they work. if the libui examples don't work, the problem is probably unrelated to Ruby.

I will reopen this issue. If you are reading this and can't get LibUI to work on Windows, please post your environment here. (Or start a new issue).

**Comment by AndyObtiva** [comment] 2021-12-05 19:04
@kojix2 I tried your suggestion to run [binary C libui examples](https://github.com/andlabs/libui/releases) in the Windows that I had trouble with in the past (Windows 10 x64 running in VirtualBox on top of Mac Catalina or Big Sur) [Windows 10 on a real machine had no issues]

The examples ran successfully. I was able to run histogram and control gallery from these groups:
-  [examples-alpha4.1-windows-amd64-mingw-static.zip](https://github.com/andlabs/libui/releases/download/alpha4.1/examples-alpha4.1-windows-amd64-mingw-static.zip)
-  [examples-alpha4.1-windows-amd64-msvc2017-static.zip](https://github.com/andlabs/libui/releases/download/alpha4.1/examples-alpha4.1-windows-amd64-msvc2017-static.zip)

This must be a Ruby issue then?

**Comment by kojix2** [comment] 2021-12-05 22:06
Thanks @AndyObtiva 

Then it might be a Ruby problem. At least, we might be able to do something about it.
Fiddle maintainer, @kou, [said](https://gitter.im/red-data-tools/ja) that the DLLs that libui.dll depends on may not exist in some Windows environments.

> The DLLs used by libui.dll include `MSVCP140.dll` and `VCRUNTIME140.dll`. Are these DLLs included in RubyInstaller? If not, I think you will get a load error.

> List of DLLs on which libui.dll depends
```
$ objdump -p vendor/libui.dll | grep -i dll
vendor/libui.dll:     ファイル形式 pei-x86-64
    DLL
DllCharacteristics    00000160
 vma:            Hint    Time      Forward  DLL       First
    DLL Name: USER32.dll
    DLL Name: KERNEL32.dll
    DLL Name: GDI32.dll
    DLL Name: UxTheme.dll
    DLL Name: d2d1.dll
    DLL Name: DWrite.dll
    DLL Name: ole32.dll
    DLL Name: MSVCP140.dll
    DLL Name: VCRUNTIME140.dll
    DLL Name: api-ms-win-crt-math-l1-1-0.dll
    DLL Name: api-ms-win-crt-runtime-l1-1-0.dll
    40142       63  _seh_filter_dll
    DLL Name: api-ms-win-crt-convert-l1-1-0.dll
    DLL Name: api-ms-win-crt-stdio-l1-1-0.dll
    DLL Name: api-ms-win-crt-string-l1-1-0.dll
    DLL Name: api-ms-win-crt-utility-l1-1-0.dll
    DLL Name: api-ms-win-crt-heap-l1-1-0.dll
名前                 000000000003ca0e libui.dll
```

He also said that dll problems can be investigated with [Dependency](https://github.com/lucasg/Dependencies), but I am not familiar with this. I know you are busy, but you could check it out if you would like to.

**Comment by AndyObtiva** [comment] 2021-12-05 22:52
My mind is blown!!!

I ran dependencies, loaded libui.dll with it, and it said it loaded fine:
![dependencies-libui-dll](https://user-images.githubusercontent.com/23052/144767084-87a057d6-c0e9-4223-94c2-86529cbae001.png)

Next, I tried running glimmer-dsl-libui meta-example, and IT WORKED!!!

![glimmer-dsl-libui-windows-meta-example](https://user-images.githubusercontent.com/23052/144767122-09438eb4-27fd-425f-a65c-c8fc5ff0d91e.png)


I don't know how! I am worried that dependencies might have brought over the dlls that are missing! I don't know. Oh well! So much for this issue. If I encounter on another machine or virtual machine, I will report again.

**Comment by Delikt** [comment] 2022-01-26 12:36
Hi, i got a solution for my Issue #48 - maybe this fix also this Error:

https://github.com/kojix2/LibUI/issues/48#issuecomment-1022022263

**Comment by kojix2** [comment] 2022-01-28 00:42
This issue is closed because it was confirmed that there is a case of missing dlls when libui does not work on Windows.
A link to issue #48 and comments will be included in the README.

However, there may still be other people who cannot get libui to work on Windows. If so, please create a new issue as this is a different issue.

**Closed by kojix2** 2022-01-28 00:42 UTC

**Comment by AndyObtiva** [comment] 2022-01-28 01:08
One thing I neglected to mention before is that I also installed something called the [WiX Toolset](https://wixtoolset.org/), which enables building Windows installers for applications. It might have as well brought the Visual C++ Redistributable with it. I wouldn’t be surprised if it did. 

That said, to be honest, I don’t think this issue is resolved if it is confirmed that dll’s are sometimes missing. After all, the fix expects developers to install a developer toolkit (the VC++ redistributable). That means, they cannot just install the LibUI Ruby gem and expect it to work (one of the strongest selling points of LibUI). 

Also, the issue is a bit unpredictable since it seems LibUI does work out of the box on some Windows systems of non-developers. 

I think more attention need to be spent on ensuring the LibUI Ruby gem works out of the box on Windows. For example, by trying to include more binaries for Windows just in case they are missing. Keep in mind that Ruby developers use a dynamic programming language because they seek convenience above all else. They usually don’t care about memory and speed so much as long as they are reasonably within the limits of their machine. The developers who care so much about things other than convenience don’t use Ruby to begin with. They just resort to C, C++, Objective C, Swift, Java or Crystal instead. But when using Ruby, it is for tasks that are not too memory, disk, or performance sensitive. And, that constitutes more than 80% of software engineer business tasks these days. That’s why Rails is so successful despite obviously not being as optimal as using Java or C++ in performance. Anyways, in summary, it is very important to keep convenience as one of the top goals in any Ruby library. 

Cheers and thank you for keeping LibUI alive and as convenient as it is for use. I look forward to continued attention to supporting productivity and maintainability with it.

**Comment by kojix2** [comment] 2022-01-28 02:00
I can think of a solution in two directions.

(1) To raise an error when Fiddle detects a missing DLL and display it in LibUI to prompt the user to install Visual C++ Redistributable. However, according to kou, Fiddle is unable to detect missing DLLs due to Windows limitations. Therefore, this method is not possible at the moment. But there may be a way we don't know of.

(2) To include frequently missing libraries in gem. This is also an issue of the C libui and depends on what the future release of libui-ng will be. There might be a way to use a custom libui.dll with Ruby's LibUI, but I don't want to do that because it would be too complicated for me.

I totally agree with you about the culture of Ruby and the benefits of the ecosystem. It certainly feels that way.

**Comment by kojix2** [comment] 2022-02-05 02:35
I reported it to Upstream...
https://github.com/libui-ng/libui-ng/issues/67
